mybatis:
  type-aliases-package: cn.andy.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
spring:
  datasource:
    url: jdbc:mysql://47.105.177.77:3306/springboot?useSSL=false&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: Gaosheng
    driver-class-name: org.gjt.mm.mysql.Driver